# Generated by Django 3.2.16 on 2024-05-07 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laws',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('text', models.TextField()),
                ('year', models.BigIntegerField()),
                ('author_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='catalog.authors')),
                ('section_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.sections')),
            ],
        ),
        migrations.DeleteModel(
            name='Law',
        ),
    ]
