# Generated by Django 3.2.16 on 2024-05-09 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20240507_1408'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authors',
            options={'verbose_name': 'учёный', 'verbose_name_plural': 'Учёные'},
        ),
        migrations.AlterModelOptions(
            name='laws',
            options={'verbose_name': 'закон', 'verbose_name_plural': 'Законы'},
        ),
        migrations.AlterModelOptions(
            name='sections',
            options={'verbose_name': 'раздел', 'verbose_name_plural': 'Разделы'},
        ),
        migrations.AlterField(
            model_name='laws',
            name='author_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.authors', verbose_name='закон'),
        ),
        migrations.AlterField(
            model_name='laws',
            name='section_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laws', to='catalog.sections', verbose_name='раздел'),
        ),
        migrations.AlterField(
            model_name='laws',
            name='text',
            field=models.TextField(verbose_name='Закон'),
        ),
        migrations.AlterField(
            model_name='laws',
            name='title',
            field=models.CharField(max_length=256, verbose_name='название закона'),
        ),
        migrations.AlterField(
            model_name='laws',
            name='year',
            field=models.BigIntegerField(verbose_name='год'),
        ),
        migrations.AlterField(
            model_name='sections',
            name='section',
            field=models.CharField(max_length=128, verbose_name='раздел'),
        ),
    ]
