# Generated by Django 3.2.16 on 2024-05-28 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20240509_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='laws',
            name='formula',
            field=models.ImageField(blank=True, upload_to='formulas', verbose_name='формула'),
        ),
    ]
